/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Migrations } from "./Migrations";
export type { PropertyNFT } from "./PropertyNFT";
export type { PropertyValuation } from "./PropertyValuation";
